# ~/.config/starship.toml
# https://starship.rs/config/

# Wait 20 milliseconds for starship to check files under the current directory.
scan_timeout = 20

# Wait 300 milliseconds for commands executed by starship
command_timeout = 300

[[battery.display]]
threshold = 25
style     = "bold red"

[directory]
truncation_length = 3
truncate_to_repo  = false

[memory_usage]
disabled  = false
threshold = 80
style     = "bold dimmed green"

[hostname]
ssh_only = true
format   =  "on [$hostname](bold blue) "
disabled = false

[git_branch]
symbol = ""

[status]
disabled = false

[shell]
disabled = false

[terraform]
format = "[ğŸğŸ’¨ $version]($style) "

[aws]
format = "on [$symbol$region]($style) "
style  = "bold blue"
symbol = "ğŸ…° "

[kubernetes]
disabled = false

[gcloud]
disabled = true
